// Default workflow data — used to seed Supabase via supabase/seed.sql
// Also used as fallback if Supabase isn't connected yet.

export const WORKFLOW_TYPES = [
  {
    slug: 'youtube-short',
    name: 'YouTube Short',
    description: 'Vertical short-form video under 60 seconds',
    icon: '⚡',
    color: '#ff0000',
  },
  {
    slug: 'youtube-longform',
    name: 'YouTube Longform',
    description: 'Full-length educational or entertainment video',
    icon: '🎬',
    color: '#ff4444',
  },
  {
    slug: 'tweet',
    name: 'Tweet / X Post',
    description: 'High-impact text post with optional media',
    icon: '𝕏',
    color: '#1da1f2',
  },
  {
    slug: 'instagram-post',
    name: 'Instagram Post',
    description: 'Feed image or carousel post',
    icon: '📸',
    color: '#e1306c',
  },
  {
    slug: 'instagram-reel',
    name: 'Instagram Reel',
    description: 'Short vertical video for Instagram',
    icon: '🎞️',
    color: '#833ab4',
  },
  {
    slug: 'linkedin-post',
    name: 'LinkedIn Post',
    description: 'Professional thought-leadership content',
    icon: '💼',
    color: '#0077b5',
  },
  {
    slug: 'tiktok',
    name: 'TikTok',
    description: 'Trend-driven short-form video',
    icon: '🎵',
    color: '#69c9d0',
  },
]

// ─── YouTube Short ─────────────────────────────────────────────────────────────
export const YOUTUBE_SHORT_STAGES = [
  {
    name: 'Idea',
    icon: '💡',
    description: 'Find and validate your hook angle',
    order_index: 0,
    tasks: [
      {
        title: 'Research trending topics in your niche',
        description: 'Identify what is already working before creating',
        instructions: `Go to YouTube → search [your niche keyword] → filter by "This Week" → sort by View Count.\n\nFind 3 videos with 100k+ views. For each one, note:\n• What is the hook in the first 3 seconds?\n• What made someone stop scrolling?\n• What format did they use (talking head / text overlay / B-roll)?\n\nScreenshot or bookmark all 3.`,
        order_index: 0,
        estimated_minutes: 10,
        has_prompt: false,
      },
      {
        title: 'Write your 1-line concept',
        description: 'Distil the video into a single clear sentence',
        instructions: `Complete this sentence (under 15 words):\n\n"This Short teaches [specific viewer] how to [specific outcome] in [timeframe/method]."\n\nExample: "This Short teaches freelancers how to raise their rates in 48 hours."\n\nIf you can't complete it cleanly → your idea isn't focused enough yet. Try again.`,
        order_index: 1,
        estimated_minutes: 5,
        has_prompt: false,
      },
      {
        title: 'Validate the hook out loud',
        description: 'Gut-check before investing time in production',
        instructions: `Say your hook out loud as if talking to a friend.\n\nAsk yourself:\n• Would I stop scrolling for this?\n• Is the payoff clear within 3 seconds?\n• Does it create curiosity or promise a specific outcome?\n\nIf YES to all three → move on.\nIf NO to any → rewrite the hook angle and repeat.`,
        order_index: 2,
        estimated_minutes: 5,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Hook & Script',
    icon: '✍️',
    description: 'Write the hook and tight script',
    order_index: 1,
    tasks: [
      {
        title: 'Write 5 hook variations',
        description: 'Generate options before committing',
        instructions: `Write 5 different opening lines for your Short. Each hook must:\n✓ Start with action, a bold claim, or a question\n✓ Include the word "you" or speak directly to viewer\n✓ Be speakable in under 6 seconds\n✓ Create curiosity or promise a clear payoff\n\nWrite all 5 now → circle the strongest one.`,
        order_index: 0,
        estimated_minutes: 10,
        has_prompt: false,
      },
      {
        title: 'Script the body (150–200 words)',
        description: 'Keep it punchy and under 58 seconds',
        instructions: `Structure:\n1. HOOK (your chosen line from previous task)\n2. TENSION/PROBLEM (1-2 sentences — why this matters)\n3. PAYOFF (3 rapid tips OR 1 reveal — the actual value)\n4. CTA (1 sentence: "Follow for more [X]" or "Comment [Y] below")\n\nRead it out loud and time yourself. Must land under 58 seconds.\nIf over → cut the weakest tip or tighten each sentence.\nNever pad. Every word earns its place.`,
        order_index: 1,
        estimated_minutes: 15,
        has_prompt: false,
      },
      {
        title: 'Refine with Claude',
        description: 'Use AI to punch up your script',
        instructions: `Copy your script and paste it into Claude with this exact prompt:\n\n"Rewrite this YouTube Short script to sound more conversational and punchy. Keep it under 200 words. Start with the hook line exactly as written. No fluff, no filler. Make every sentence land harder."\n\nReview the output → take the best elements from both versions → write your final script.`,
        order_index: 2,
        estimated_minutes: 10,
        has_prompt: true,
        prompt_text: 'Rewrite this YouTube Short script to sound more conversational and punchy. Keep it under 200 words. Start with the hook line exactly as written. No fluff, no filler. Make every sentence land harder.\n\n[PASTE YOUR SCRIPT HERE]',
      },
      {
        title: 'Print or prep script for recording',
        description: 'Get it in front of you before hitting record',
        instructions: `• Copy final script to your phone notes OR print it\n• Read it aloud one more time — at full energy, not quietly\n• Highlight any words you want to emphasise\n• Put the script somewhere you can glance at during recording (but not read robotically)\n\nYou're ready to record.`,
        order_index: 3,
        estimated_minutes: 5,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Recording',
    icon: '🎥',
    description: 'Get the footage you need',
    order_index: 2,
    tasks: [
      {
        title: 'Set up your shot',
        description: 'Check all technical settings before recording',
        instructions: `Run through this checklist before pressing record:\n\n✓ FRAMING: Camera shooting vertically (9:16) and at eye level\n✓ LIGHT: No harsh shadows on face — ring light or face a window\n✓ AUDIO: Mic plugged in / Lavalier clipped on / room is quiet\n✓ BACKGROUND: Clean, intentional, or blurred — no clutter\n✓ CAMERA: Recording in at least 1080p\n✓ PHONE OFF: Do Not Disturb mode on\n\nDon't start recording until every item is checked.`,
        order_index: 0,
        estimated_minutes: 10,
        has_prompt: false,
      },
      {
        title: 'Record minimum 3 full takes',
        description: 'Quantity gives you options in editing',
        instructions: `Rules:\n• NEVER stop mid-take — power through any mistake, keep going\n• Vary your energy:\n  Take 1 → Normal pace, conversational\n  Take 2 → 20% faster, more urgent energy\n  Take 3 → Most confident, highest energy you've got\n\n• Clap hands at the start of each take (helps sync in editing)\n• You need at least 3 before you're allowed to stop recording.`,
        order_index: 1,
        estimated_minutes: 20,
        has_prompt: false,
      },
      {
        title: 'Select your best take',
        description: 'Choose with your gut, not your inner critic',
        instructions: `Step 1: Watch all 3 takes on MUTE → pick most energetic body language.\nStep 2: Watch your top pick WITH sound → confirm audio is clean.\nStep 3: Check: does the hook land in the first 3 seconds?\n\nIf YES → mark that take and move to Assets.\nIf the audio is bad on all takes → re-record. Don't compromise on audio.\n\nTip: You will always hate how you look/sound. Pick the best one anyway.`,
        order_index: 2,
        estimated_minutes: 5,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Assets',
    icon: '🗂️',
    description: 'Gather all media before editing',
    order_index: 3,
    tasks: [
      {
        title: 'Pull 3 memes or reaction clips',
        description: 'Cutaway visuals that reinforce your points',
        instructions: `Go to your memes folder (create one if you don't have it — start saving memes now).\n\nAlternatives if you don't have any:\n• giphy.com → search [your topic or emotion]\n• knowyourmeme.com\n• Google Images → [topic] + "meme"\n\nFind 3 images or GIFs that match moments in your script.\nSave them to a dedicated folder: [ProjectName]/Assets/Memes/`,
        order_index: 0,
        estimated_minutes: 10,
        has_prompt: false,
        resource_url: 'https://giphy.com',
      },
      {
        title: 'Download 2 stock video clips from Pexels',
        description: 'Free B-roll to make cuts visually dynamic',
        instructions: `Go to pexels.com/videos\n\nSearch [your topic keyword] — be specific (e.g., "person working laptop" not just "work").\n\nDownload 2 clips:\n✓ Under 10 seconds each\n✓ HD quality (1080p minimum)\n✓ Relevant to your script topic\n\nSave to: [ProjectName]/Assets/Stock/\n\nTip: Download 4–5 options so you have backups.`,
        order_index: 1,
        estimated_minutes: 10,
        has_prompt: false,
        resource_url: 'https://pexels.com/videos',
      },
      {
        title: 'Find background music',
        description: 'A music bed makes your Short feel polished',
        instructions: `Go to one of these sources (all copyright-free):\n• YouTube Audio Library: studio.youtube.com → Audio Library\n• Pixabay Music: pixabay.com/music\n• Uppbeat: uppbeat.io (free tier)\n\nSearch mood: upbeat / energetic / motivational\nDuration: longer than your Short is fine — you'll trim it.\n\nDownload 1 track and save to: [ProjectName]/Assets/Music/\nNote the track name for description credits.`,
        order_index: 2,
        estimated_minutes: 10,
        has_prompt: false,
        resource_url: 'https://studio.youtube.com',
      },
    ],
  },
  {
    name: 'Editing',
    icon: '✂️',
    description: 'Cut, caption, and polish',
    order_index: 4,
    tasks: [
      {
        title: 'Create project and import all media',
        description: 'Set up your timeline correctly first time',
        instructions: `Open your editor (CapCut / Premiere / DaVinci).\n\nNew project settings:\n• Resolution: 1080 x 1920 (vertical)\n• Frame rate: 30fps\n• Colour space: sRGB\n\nImport everything:\n✓ Your best take (main recording)\n✓ All B-roll clips\n✓ Memes / reaction images\n✓ Background music track\n\nDrop main recording onto timeline first.`,
        order_index: 0,
        estimated_minutes: 5,
        has_prompt: false,
      },
      {
        title: 'Rough cut — remove all dead air',
        description: 'The most important edit you will make',
        instructions: `Go through your main recording and cut:\n✗ Every pause longer than 0.5 seconds\n✗ Every "um", "uh", "like", "you know"\n✗ Any stumbled words before you recovered\n✗ Silence at start and end of clip\n\nAfter rough cut, your timeline should feel rapid — no breathing room.\nTotal runtime should be 45–58 seconds.\n\nIf it's over 60 → cut the weakest tip or tightest a section more.`,
        order_index: 1,
        estimated_minutes: 20,
        has_prompt: false,
      },
      {
        title: 'Add B-roll cutaways',
        description: 'Every 3–4 seconds, change the visual',
        instructions: `Rule: Never more than 4 seconds on talking head without a visual cut.\n\nPlace your B-roll clips and memes at natural cut points in the script.\nBest moments to cut away:\n• When you mention a concept ("for example…") → cut to example clip\n• During a list item → cut to relevant meme or footage\n• Between tips → reset with B-roll\n\nAdd smooth cuts (J-cut or L-cut). No wipes or fades — just clean cuts.`,
        order_index: 2,
        estimated_minutes: 15,
        has_prompt: false,
      },
      {
        title: 'Add captions',
        description: 'Captions double watch time — do not skip this',
        instructions: `Option A (fastest) — CapCut auto-captions:\nText → Auto Captions → Generate → review and fix errors.\n\nOption B — Manual:\nType captions yourself, synced to speech.\n\nCaption style rules:\n✓ 2–3 words per line maximum\n✓ Bold white text\n✓ Black drop shadow or dark outline\n✓ Positioned centre or lower-centre\n✓ Large enough to read on a phone screen\n\nHighlight key words in yellow or cyan.`,
        order_index: 3,
        estimated_minutes: 15,
        has_prompt: false,
      },
      {
        title: 'Add music and export',
        description: 'Final polish before exporting',
        instructions: `1. Drop your music track on a separate track below everything else.\n2. Set music volume to 10–15% (voice must be louder).\n3. Add fade in: first 2 seconds / Fade out: last 2 seconds.\n4. Watch the whole thing one final time — check:\n   ✓ Captions sync to audio\n   ✓ Music doesn't overpower voice\n   ✓ Total runtime ≤ 60 seconds\n\nExport settings:\n• Format: MP4 / H.264\n• Resolution: 1080 x 1920\n• Frame rate: 30fps\n• Bitrate: 10–15 Mbps\n• Audio: Stereo, 44.1kHz`,
        order_index: 4,
        estimated_minutes: 10,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Upload',
    icon: '🚀',
    description: 'Publish and optimise for discovery',
    order_index: 5,
    tasks: [
      {
        title: 'Write your title',
        description: 'Keyword-first title that earns the click',
        instructions: `Formula: [Strong Action Verb] + [Specific Outcome] + [Optional: "#Shorts" or niche tag]\n\nRules:\n✓ Under 60 characters total\n✓ Front-load your main keyword (first 2–3 words)\n✓ No clickbait without delivering on the promise\n✓ Read it out loud — does it sound like something someone would say?\n\nExamples:\n✓ "Double Your Freelance Rate in 48 Hours #Shorts"\n✓ "3 Morning Habits That Changed My Life"\n✗ "This video will change everything..." (vague)`,
        order_index: 0,
        estimated_minutes: 5,
        has_prompt: false,
      },
      {
        title: 'Write description and hashtags',
        description: 'Helps search and algorithm discovery',
        instructions: `Description structure:\n• Line 1: Your hook sentence (same as your opening line)\n• Line 2: 1–2 sentence value proposition\n• Line 3: Subscribe CTA\n• Line 4-5: 3–5 hashtags\n\nHashtags: #Shorts + 2 niche-specific tags (e.g., #FreelanceTips #MakeMoneyOnline)\n\nDo NOT spam hashtags. 3–5 relevant ones beat 30 random ones.\n\nExample:\n"Stop charging by the hour — here's why it's killing your income.\nI went from $30/hr to $150/hr using this method. Follow for more freelance tips.\n#Shorts #FreelanceTips #MakeMoneyOnline"`,
        order_index: 1,
        estimated_minutes: 5,
        has_prompt: false,
      },
      {
        title: 'Upload and publish',
        description: 'Get it live at the right time',
        instructions: `Go to studio.youtube.com → Upload video.\n\n✓ Upload your exported MP4\n✓ Add title and description\n✓ Set audience: "No, it's not made for kids"\n✓ YouTube will auto-detect it's a Short (vertical + under 60s)\n✓ Thumbnail: YouTube will auto-generate — this is fine for Shorts\n\nBest upload times (general):\n• Weekdays: 3pm–7pm your audience's timezone\n• Weekends: 9am–11am\n\nPublish → then go to the video and drop a pinned comment with your CTA.`,
        order_index: 2,
        estimated_minutes: 10,
        has_prompt: false,
        resource_url: 'https://studio.youtube.com',
      },
    ],
  },
]

// ─── YouTube Longform ──────────────────────────────────────────────────────────
export const YOUTUBE_LONGFORM_STAGES = [
  {
    name: 'Idea',
    icon: '💡',
    description: 'Validate demand before committing to a full video',
    order_index: 0,
    tasks: [
      {
        title: 'Research search demand on YouTube',
        description: 'Find proven topics before creating',
        instructions: `Go to YouTube and search your topic idea.\n\nLook for:\n✓ Videos in your niche with 100k–1M+ views (proves demand)\n✓ Videos from smaller channels with high views (less competition wins = opportunity)\n✓ Gaps: what angle hasn't been done well yet?\n\nUse TubeBuddy or VidIQ (free tier) to check keyword search volume.\nTarget: monthly search volume > 1,000 with competition score < 50.\n\nNote your top 3 keyword variations.`,
        order_index: 0,
        estimated_minutes: 20,
        has_prompt: false,
      },
      {
        title: 'Define your unique angle',
        description: 'What makes YOUR take different from what already exists?',
        instructions: `Watch the top 3 videos on your topic for 2 minutes each.\n\nAnswer these questions:\n• What do they all cover? (You must cover this too)\n• What do they all miss? (Your unique angle lives here)\n• What format do they use? (Match or intentionally break the format)\n• What can you add from personal experience / data / story?\n\nWrite your angle in 1 sentence: "This video covers [topic] but specifically focuses on [unique angle] for [specific audience]."`,
        order_index: 1,
        estimated_minutes: 15,
        has_prompt: false,
      },
      {
        title: 'Validate with your audience',
        description: 'Don\'t produce what you THINK they want — confirm it',
        instructions: `If you have an audience (any size):\n• Post a Community tab poll: "Which video do you want next?" with 3 options\n• OR reply to a recent comment asking what they want\n\nIf no audience yet:\n• Check Reddit (r/[your niche]) — what questions keep getting asked?\n• Check YouTube comments on competitor videos — what do people say they want?\n• Check Quora and answer forums for your niche\n\nGreen light to proceed if you've confirmed demand from 2+ sources.`,
        order_index: 2,
        estimated_minutes: 15,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Titles & Thumbnails',
    icon: '🖼️',
    description: 'This is your most important stage — packaging drives clicks',
    order_index: 1,
    tasks: [
      {
        title: 'Write 10 title variations',
        description: 'Quantity first, then pick the winner',
        instructions: `Write 10 title options. Use these proven formulas:\n\n1. "How I [Result] in [Timeframe]"\n2. "The [Adjective] Guide to [Topic]"\n3. "[Number] [Things] That [Outcome]"\n4. "Why [Common Belief] Is Wrong (and What to Do Instead)"\n5. "I [Did Thing] for [Time Period] — Here's What Happened"\n6. "The Truth About [Topic]"\n7. "[Topic]: What Nobody Tells You"\n8. "[Number] Mistakes That Are [Negative Outcome]"\n9. "How to [Result] (Even If [Common Objection])"\n10. "[Topic] Explained in [Time/Format]"\n\nWrite all 10 before deciding — your best title is rarely your first idea.`,
        order_index: 0,
        estimated_minutes: 15,
        has_prompt: false,
      },
      {
        title: 'Design 3 thumbnail concepts',
        description: 'Think in thumbnails before you shoot',
        instructions: `Sketch or describe 3 different thumbnail concepts:\n\nEach must have:\n• ONE hero element (face / object / graphic)\n• 1–4 words of text maximum (large, bold, readable at 150px)\n• High contrast (dark on light or light on dark)\n• ONE emotion (curiosity, surprise, excitement)\n\nRules:\n✗ No more than 1–2 faces\n✗ No walls of text\n✗ No cluttered backgrounds\n✗ No clickbait images that don't match the video\n\nOpen Canva and build your best concept. Use the YouTube thumbnail template (1280x720).`,
        order_index: 1,
        estimated_minutes: 30,
        has_prompt: false,
        resource_url: 'https://canva.com',
      },
      {
        title: 'Select your best title + thumbnail combo',
        description: 'They must work together as a unit',
        instructions: `Show your thumbnail to someone who doesn't know your topic.\n\nAsk them:\n1. What do you think this video is about?\n2. Would you click on it? Why / why not?\n\nThe title and thumbnail together must answer: "Why should I watch THIS video NOW?"\n\nIf your thumbnail needs a specific shot of your face or a prop → add a recording task in the Recording stage.\n\nLock in your title and thumbnail concept before scripting.`,
        order_index: 2,
        estimated_minutes: 10,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Script',
    icon: '✍️',
    description: 'Write a tight, structured script that holds retention',
    order_index: 2,
    tasks: [
      {
        title: 'Write your outline',
        description: 'Structure first — fill in content second',
        instructions: `Your outline structure:\n\n1. HOOK (first 30 seconds)\n   - Open with your strongest moment: a surprising stat, bold claim, or story\n   - Tell them what they'll get from watching\n   - Create a "open loop" — a question or tension they need resolved\n\n2. INTRO (30–60 seconds)\n   - Who are you + why should they trust you on this?\n   - What is this video going to cover?\n\n3. BODY (3–7 main sections)\n   - Each section: point → explanation → example → transition\n\n4. OUTRO (60–90 seconds)\n   - Summary of key takeaways\n   - CTA (subscribe / watch next video / comment)\n   - Tease the next video\n\nWrite the outline first — get it approved in your head before scripting.`,
        order_index: 0,
        estimated_minutes: 20,
        has_prompt: false,
      },
      {
        title: 'Write the hook (first 30 seconds)',
        description: 'The most important 30 seconds of your video',
        instructions: `Your hook must earn the next 5 minutes of watch time.\n\nFormula that works:\n• Start with your most shocking/interesting moment ("Most people lose half their income doing this...")\n• Promise the payoff ("By the end of this video you'll know exactly how to...")\n• Create urgency ("And if you're still doing X, this video is for you")\n\nWrite 3 different hook versions → pick the best.\n\nTest: After hearing your hook, would a viewer think "I need to keep watching"? If no → rewrite.`,
        order_index: 1,
        estimated_minutes: 20,
        has_prompt: false,
      },
      {
        title: 'Write the full script body',
        description: 'Write section by section, not all at once',
        instructions: `Write each section from your outline one at a time:\n\nFor each section follow this structure:\n1. CLAIM — state the point clearly\n2. EXPLAIN — what does this mean / why does it matter?\n3. EXAMPLE — a specific story, stat, or demonstration\n4. TRANSITION — bridge to the next section\n\nTarget length:\n• 8–10 minute video: ~1,500–2,000 words\n• 15–20 minute video: ~2,500–3,500 words\n\nWrite conversationally — how you'd explain it to a smart friend. Read each section out loud as you write it.`,
        order_index: 2,
        estimated_minutes: 60,
        has_prompt: false,
      },
      {
        title: 'Refine script with Claude',
        description: 'Polish the script for flow and punch',
        instructions: `Copy each section into Claude with this prompt:\n\n"Rewrite this YouTube script section to sound more natural and conversational, like a smart friend explaining this topic. Cut anything repetitive. Make the examples more specific and vivid. Keep the same length or shorter."\n\nDo this section by section — don't paste the whole script at once.\n\nFinal check:\n✓ Read the whole script out loud (target under [your video length])\n✓ Mark timestamps in script as you read\n✓ Highlight any section that loses your attention → tighten it`,
        order_index: 3,
        estimated_minutes: 30,
        has_prompt: true,
        prompt_text: 'Rewrite this YouTube script section to sound more natural and conversational, like a smart friend explaining this topic. Cut anything repetitive. Make the examples more specific and vivid. Keep the same length or shorter.\n\n[PASTE SECTION HERE]',
      },
    ],
  },
  {
    name: 'Recording',
    icon: '🎥',
    description: 'Capture clean footage efficiently',
    order_index: 3,
    tasks: [
      {
        title: 'Set up your recording space',
        description: 'Get technical details right before touching the camera',
        instructions: `Studio checklist:\n\n✓ CAMERA: 1080p minimum, 4K ideal — set to horizontal (16:9)\n✓ FRAME: Camera at eye level or very slightly above — never below\n✓ LIGHT: Key light on face at 45° angle, fill light or bounce to reduce shadows\n✓ BACKGROUND: Intentional — bookshelf, branded wall, or clean plain colour\n✓ AUDIO: Lavalier mic or USB condenser mic — test levels first\n✓ TELEPROMPTER: Use your phone (Teleprompter Premium app) or print script\n✓ ROOM: AC off, phone on Do Not Disturb, door sign on\n\nRecord a 10-second test clip and watch it back before recording for real.`,
        order_index: 0,
        estimated_minutes: 20,
        has_prompt: false,
      },
      {
        title: 'Record in sections (not one take)',
        description: 'Shorter takes = better energy + easier editing',
        instructions: `Record section by section from your script:\n• Hook → stop, check playback\n• Intro → record → check\n• Body section 1 → record → move on\n• Etc.\n\nFor each section, aim for 2–3 takes. Keep all takes — don't delete on camera.\n\nClap at the start of each take (audio sync marker).\n\nIf you stumble badly, say "take [N]" then restart — don't stop recording, just pause and go again.`,
        order_index: 1,
        estimated_minutes: 90,
        has_prompt: false,
      },
      {
        title: 'Shoot thumbnail photo',
        description: 'Get the thumbnail shot while your setup is live',
        instructions: `While your recording setup is still live, shoot your thumbnail image.\n\nBased on your thumbnail concept from Stage 2, capture:\n• Your face with the required expression (shocked / excited / thoughtful)\n• Any props needed\n• 10+ different shots — you need options\n\nCheck in Canva that your chosen shot works with your thumbnail design before breaking down setup.\n\nShoot in good light, high resolution (12MP+ phone or DSLR).`,
        order_index: 2,
        estimated_minutes: 15,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Assets',
    icon: '🗂️',
    description: 'Gather all media before you open your editor',
    order_index: 4,
    tasks: [
      {
        title: 'Write B-roll shot list',
        description: 'Plan what you need before hunting for it',
        instructions: `Go through your script and mark every point where a visual would help:\n• Concept explanations → screenshot / diagram / animation\n• Real-world examples → stock footage or screen recording\n• Statistics → text animation or chart\n• Tools/products mentioned → screen recording or product footage\n\nCreate a list:\n[ ] B-roll 1: [what it shows] → [source: screen rec / Pexels / own footage]\n[ ] B-roll 2: ...\n\nAim for a visual change every 3–5 seconds in editing.`,
        order_index: 0,
        estimated_minutes: 15,
        has_prompt: false,
      },
      {
        title: 'Gather stock footage and images',
        description: 'Download everything you need before editing',
        instructions: `Sources:\n• Video: pexels.com/videos, pixabay.com, mixkit.co\n• Images: unsplash.com, pexels.com\n• Charts/data: Create in Google Sheets and screenshot\n\nFor each B-roll item on your list:\n1. Search for it now\n2. Download the best option + 1–2 backups\n3. Save to [ProjectName]/Assets/Stock/\n\nDo NOT start editing until this folder is complete.`,
        order_index: 1,
        estimated_minutes: 20,
        has_prompt: false,
        resource_url: 'https://pexels.com/videos',
      },
      {
        title: 'Record screen captures (if needed)',
        description: 'Software demos, walkthroughs, and tool tutorials',
        instructions: `If your video includes any tool demos, walkthroughs, or on-screen content:\n\nTool: Loom (free) or OBS (free) or QuickTime (Mac)\n\nSettings:\n• Record at 1080p minimum\n• Hide your desktop icons and personal folders\n• Close unrelated tabs\n• Use a clean browser profile\n\nRecord each demo in one take — it's easier to trim than to splice screen recordings.\n\nSave to [ProjectName]/Assets/Screen Recordings/`,
        order_index: 2,
        estimated_minutes: 30,
        has_prompt: false,
      },
      {
        title: 'Get background music and sound effects',
        description: 'Audio polish separates good videos from great ones',
        instructions: `Music:\n• YouTube Audio Library → background / cinematic / lo-fi depending on your tone\n• Artlist.io (paid, great quality)\n• Epidemicsound.com (paid subscription)\n\nSound effects (optional but addictive):\n• freesound.org — notification sounds, whooshes, transitions\n• Zapsplat.com\n\nDownload:\n✓ 1 main background track (lower energy, doesn't distract)\n✓ 1 intro/outro stinger (higher energy)\n✓ 3–5 sound effects for emphasis (ding, whoosh, etc.)\n\nSave to [ProjectName]/Assets/Audio/`,
        order_index: 3,
        estimated_minutes: 15,
        has_prompt: false,
        resource_url: 'https://studio.youtube.com',
      },
    ],
  },
  {
    name: 'Editing',
    icon: '✂️',
    description: 'Assemble, cut, and polish the full video',
    order_index: 5,
    tasks: [
      {
        title: 'Set up project and rough assembly',
        description: 'Lay everything out before fine cutting',
        instructions: `New project:\n• Resolution: 1920x1080 (16:9)\n• Frame rate: 24fps or 30fps (match your recording)\n\nImport all files:\n✓ All camera recordings\n✓ Stock footage / screen recordings\n✓ Images\n✓ Audio files\n\nRough assembly:\n1. Drop all sections in order onto the timeline\n2. Pick the best take of each section (don't worry about micro-edits yet)\n3. Just get it in order — rough cut only\n4. Check the total rough cut length`,
        order_index: 0,
        estimated_minutes: 30,
        has_prompt: false,
      },
      {
        title: 'Fine cut — tighten every section',
        description: 'Remove every second that doesn\'t earn its place',
        instructions: `Go section by section and cut:\n✗ All pauses longer than 0.5 seconds\n✗ All "ums", "uhs", "likes", "you knows"\n✗ Any line you stumbled over and re-did\n✗ Anything repetitive to what you said 3 sentences ago\n✗ Long preambles before you get to the point\n\nTip: Jump cuts are fine for YouTube — viewers expect them.\nTip: Use J-cuts and L-cuts for smooth transitions between sections.\n\nTarget: Get the talking head footage as tight as possible before adding B-roll.`,
        order_index: 1,
        estimated_minutes: 60,
        has_prompt: false,
      },
      {
        title: 'Add B-roll and screen recordings',
        description: 'Cover jump cuts and add visual variety',
        instructions: `Place B-roll on a track above the main footage at every:\n• Jump cut (to hide it)\n• Concept mention ("for example…" → show the example)\n• List item (cut to visual for each point)\n• Transition between sections\n\nB-roll rules:\n✓ Must be relevant — no generic "busy office" stock footage for specific topics\n✓ Screen recordings: cut any dead clicks or loading time\n✓ Maximum 5–7 seconds on any single B-roll before cutting back to face\n\nAdd transitions: simple cross-dissolve (0.3s) between major sections. No wipes.`,
        order_index: 2,
        estimated_minutes: 45,
        has_prompt: false,
      },
      {
        title: 'Add text overlays and graphics',
        description: 'Reinforce key points visually',
        instructions: `Add text overlays for:\n✓ Chapter titles at the start of each main section\n✓ Key statistics or quotes — display as text on screen while you say them\n✓ Tool names / URLs you mention\n✓ Subscribe reminder (appears once, around 30% into video)\n\nStyle guidelines:\n• Font: clean, bold (Inter, Montserrat, or your brand font)\n• Colours: white text, or your brand colour on dark background\n• Animations: fade in / slide in — nothing flashy\n• Duration: long enough to read comfortably (minimum 3 seconds for text)\n\nAdd lower thirds for any person names or titles.`,
        order_index: 3,
        estimated_minutes: 30,
        has_prompt: false,
      },
      {
        title: 'Add music and mix audio',
        description: 'Audio quality makes or breaks audience retention',
        instructions: `Music levels:\n• Background track: 5–10% of your main voice volume\n• Intro/outro stinger: can be louder (20–30%)\n• Fade music in on first 2 seconds, fade out on last 2 seconds\n• Duck the music under any speaking (use keyframes)\n\nVoice levels:\n• Target: peaks at -6dB, average around -12dB\n• Apply gentle compression if your voice varies a lot\n• Remove background hiss with noise reduction (Premiere: DeNoise / DaVinci: Noise Reduction)\n\nExport audio test: listen on headphones AND phone speaker.`,
        order_index: 4,
        estimated_minutes: 20,
        has_prompt: false,
      },
      {
        title: 'Final review and export',
        description: 'Watch the whole thing before uploading',
        instructions: `Final watch-through checklist:\n✓ Hook grabs in first 30 seconds\n✓ No audio pops or video glitches\n✓ All text is readable\n✓ Captions are correct (if added)\n✓ Outro CTA is clear\n✓ Music fades correctly\n\nExport settings:\n• Format: H.264 / MP4\n• Resolution: 1920x1080 (or 4K: 3840x2160)\n• Frame rate: match recording (24 or 30fps)\n• Bitrate: 8–16 Mbps\n• Audio: AAC, 320kbps, Stereo\n\nFile size under 256GB (YouTube limit). Typical 10-min video: 1–3GB.`,
        order_index: 5,
        estimated_minutes: 20,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Upload',
    icon: '🚀',
    description: 'Maximise discoverability on launch',
    order_index: 6,
    tasks: [
      {
        title: 'Finalise thumbnail in Canva',
        description: 'A great thumbnail is worth 100 extra hours of editing',
        instructions: `Open your thumbnail design (from Stage 2) in Canva.\n\nFinal checklist:\n✓ Thumbnail photo (from your shoot) is in place\n✓ Text is bold, large, readable at 150px thumbnail size\n✓ Maximum 4 words on the thumbnail\n✓ High contrast (check at small size — zoom out to 20%)\n✓ Emotion on face is clear\n✓ Brand colours / style consistent with your channel\n\nExport as PNG, 1280x720, maximum quality.\n\nName the file: [VIDEO TITLE] Thumbnail.png`,
        order_index: 0,
        estimated_minutes: 20,
        has_prompt: false,
        resource_url: 'https://canva.com',
      },
      {
        title: 'Write SEO-optimised title and description',
        description: 'Structure your metadata for search and suggested',
        instructions: `Title: Use your best version from Stage 2. Confirm:\n✓ Target keyword in first 3 words\n✓ Under 60 characters\n✓ Compelling without being clickbait\n\nDescription (first 2–3 lines show above "Show more" — most important):\nLine 1: Hook sentence / value proposition\nLine 2: What they'll learn\nLine 3: "Subscribe for [topic] videos every [cadence]"\n\nFull description:\n• Timestamps for all main sections (add these after upload)\n• Links to tools/resources mentioned\n• Links to related videos\n• Social media links\n• 3–8 relevant hashtags at the bottom`,
        order_index: 1,
        estimated_minutes: 15,
        has_prompt: false,
      },
      {
        title: 'Upload, schedule, and publish',
        description: 'Get it live at the optimal time',
        instructions: `Go to studio.youtube.com → Upload.\n\nDuring upload:\n✓ Add title and description\n✓ Add custom thumbnail\n✓ Add to relevant playlist\n✓ Set audience (not for kids)\n✓ Add cards and end screen (after video is processed)\n✓ Add chapters in description (format: 0:00 - Intro)\n\nSchedule time:\n• Check your YouTube Analytics → Audience tab → When your viewers are on YouTube\n• Typically: Mon–Thu, 3pm–6pm your audience timezone performs well\n\nAfter publishing:\n• Pin a comment with your CTA immediately\n• Post about it on other social channels`,
        order_index: 2,
        estimated_minutes: 15,
        has_prompt: false,
        resource_url: 'https://studio.youtube.com',
      },
    ],
  },
]

// ─── Tweet ─────────────────────────────────────────────────────────────────────
export const TWEET_STAGES = [
  {
    name: 'Idea',
    icon: '💡',
    description: 'Find the angle that will resonate',
    order_index: 0,
    tasks: [
      {
        title: 'Choose your tweet type',
        description: 'Different formats serve different goals',
        instructions: `Pick one type for this tweet:\n\n1. INSIGHT — a counterintuitive truth in your niche\n2. STORY — a personal experience with a lesson\n3. HOT TAKE — a strong opinion others are afraid to say\n4. TIP — one specific actionable tip\n5. LIST — 5–10 items on a theme\n6. QUESTION — engage your audience directly\n7. THREAD — multi-tweet deep dive on one topic\n\nThe best performing tweets are:\n✓ Specific not vague\n✓ Have a clear point of view\n✓ Make the reader feel seen, taught, or challenged\n\nChoose your type and write it at the top of your notes.`,
        order_index: 0,
        estimated_minutes: 5,
        has_prompt: false,
      },
      {
        title: 'Write a 1-sentence core idea',
        description: 'If you can\'t say it in one sentence, you don\'t know it yet',
        instructions: `Write the core idea of your tweet in exactly one sentence.\n\nThis isn't the tweet itself — it's what the tweet MEANS.\n\nExample:\n• Core idea: "Most people fail at habits because they set goals instead of systems"\n• Tweet: (will be crafted from this)\n\nIf you can't write the core idea clearly in one sentence → pick a different topic.\nYou must know exactly what point you're making before writing the tweet.`,
        order_index: 1,
        estimated_minutes: 5,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Write',
    icon: '✍️',
    description: 'Draft and sharpen your tweet',
    order_index: 1,
    tasks: [
      {
        title: 'Write 3 draft versions',
        description: 'Your first draft is almost never your best',
        instructions: `Write 3 completely different versions of your tweet:\n\nVersion 1: Direct statement\nVersion 2: Start with a story or scenario\nVersion 3: Start with a surprising/counterintuitive opener\n\nFor each version:\n✓ First line must hook BEFORE the "Read more" cutoff (under 280 chars for single, under ~110 chars for threads)\n✓ Clear point — no vagueness\n✓ Ends with either a punchline, a takeaway, or a question\n✓ No hashtags in the body (put them at the end if at all)\n\nWrite all 3 before judging any of them.`,
        order_index: 0,
        estimated_minutes: 15,
        has_prompt: false,
      },
      {
        title: 'Sharpen your best version',
        description: 'Cut ruthlessly until every word earns its place',
        instructions: `Pick your best draft from the 3 versions.\n\nNow edit it ruthlessly:\n✗ Cut every filler word (very, really, just, actually, basically)\n✗ Cut every sentence that doesn't add new information\n✗ Replace passive voice with active voice\n✗ Make vague words specific (not "a lot" → "3x more")\n✗ Cut "I think" and "in my opinion" — just say the thing\n\nRead it out loud. Does every line pull you to the next? If not, keep cutting.\n\nFor threads: First tweet must work standalone. Each subsequent tweet must add new value — not just repeat.`,
        order_index: 1,
        estimated_minutes: 10,
        has_prompt: false,
      },
      {
        title: 'Add media if it helps',
        description: 'Visuals increase engagement by ~3x',
        instructions: `Does your tweet benefit from an image, chart, or video?\n\nYES: Attach it. Types that work well:\n• Screenshot of a result, stat, or conversation\n• Simple chart or graph (Canva: Twitter Post template)\n• Before/after comparison\n• Short video clip (under 30 seconds)\n\nNO: Don't force it. Pure text tweets that are great get more reach than mediocre tweets with images.\n\nIf adding an image — write an alt text description for accessibility.`,
        order_index: 2,
        estimated_minutes: 10,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Post & Engage',
    icon: '🚀',
    description: 'Post at the right time and drive early engagement',
    order_index: 2,
    tasks: [
      {
        title: 'Post at optimal time',
        description: 'Timing impacts the first hour of reach dramatically',
        instructions: `Best times to post (generally):\n• Mon–Thu: 8–10am, 12–1pm, 5–7pm\n• Fri: 8–10am, 12–1pm (engagement drops after 3pm)\n• Weekends: 9–11am\n\nYour personal best times:\n→ Check X/Twitter Analytics → Tweets tab → sort by engagement → look at what times your top tweets went live\n\nPost now OR schedule using Buffer, Typefully, or X's native scheduling.\n\nImmediately after posting: Be available for the first 30 minutes. Reply to every comment — early engagement signals boost algorithmic reach.`,
        order_index: 0,
        estimated_minutes: 5,
        has_prompt: false,
      },
      {
        title: 'Engage for 30 minutes post-posting',
        description: 'Reply to every comment in the first 30 minutes',
        instructions: `The first 30 minutes after posting are critical for algorithmic reach.\n\nRules:\n✓ Reply to every comment (even just "thanks" + a follow-up question)\n✓ Like your own top comments\n✓ Quote-tweet with additional context if it picks up traction\n✓ Share to other platforms (LinkedIn, Instagram Story, etc.)\n\nDo NOT:\n✗ Post and disappear immediately\n✗ Delete and repost (hurts reach)\n✗ Edit the tweet in first 30 minutes\n\nSet a 30-minute timer and stay engaged.`,
        order_index: 1,
        estimated_minutes: 30,
        has_prompt: false,
      },
    ],
  },
]

// ─── Instagram Post ─────────────────────────────────────────────────────────
export const INSTAGRAM_POST_STAGES = [
  {
    name: 'Concept',
    icon: '💡',
    description: 'Define what this post is and who it\'s for',
    order_index: 0,
    tasks: [
      {
        title: 'Choose post format',
        description: 'Format determines the creation workflow',
        instructions: `Choose one:\n\n1. SINGLE IMAGE — one strong visual + caption\n2. CAROUSEL (2–10 slides) — swipeable multi-page content (highest reach currently)\n3. INFOGRAPHIC — visual representation of data or a framework\n\nCarousels currently get 3x more reach than single images on Instagram.\nIf you have 3+ points to make → use a carousel.\n\nOnce chosen, write it down and move on.`,
        order_index: 0,
        estimated_minutes: 3,
        has_prompt: false,
      },
      {
        title: 'Write your hook for slide 1',
        description: 'The first slide determines whether they swipe or scroll past',
        instructions: `Slide 1 = your thumbnail. It must stop the scroll.\n\nFormulas that work:\n• "X things I wish I knew about [topic]"\n• "[Bold claim] (and most people get this wrong)"\n• "Stop [doing thing]. Do [this] instead."\n• "How I [result] without [common method]"\n\nThe text on Slide 1 should:\n✓ Be under 7 words\n✓ Create curiosity or promise a specific outcome\n✓ Be readable at mobile thumbnail size\n\nWrite 3 options → pick the best one.`,
        order_index: 1,
        estimated_minutes: 10,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Design',
    icon: '🎨',
    description: 'Create the visual content',
    order_index: 1,
    tasks: [
      {
        title: 'Set up Canva template',
        description: 'Start from the right canvas size',
        instructions: `Open Canva → New Design → Instagram Post (1080x1080) for square OR Instagram Story (1080x1920) for vertical carousel.\n\nFor carousel:\n• Create multiple pages in Canva (one page per slide)\n• Keep brand consistency: same fonts, colours, and style across all slides\n\nBrand consistency checklist:\n✓ Maximum 2 fonts (one heading, one body)\n✓ Your brand colours only (no random colours)\n✓ Same border/padding on every slide\n✓ Your handle or logo on every slide (small, bottom corner)\n\nIf you don't have brand assets → pick ONE font and ONE accent colour and stick to it.`,
        order_index: 0,
        estimated_minutes: 10,
        has_prompt: false,
        resource_url: 'https://canva.com',
      },
      {
        title: 'Design all slides',
        description: 'Create each slide in order',
        instructions: `For each slide:\n• Slide 1: Hook (bold text, strong visual, curiosity)\n• Slides 2–N: One point per slide — keep it simple, visual hierarchy\n• Last slide: CTA ("Follow for more [X]" + your handle)\n\nDesign rules:\n✓ One main idea per slide\n✓ Large text — readable on a phone without zooming\n✓ Lots of white space — don't crowd it\n✓ Images that are high quality and relevant\n✗ No walls of text\n✗ No more than 3 visual elements per slide\n\nDesign all slides before moving on.`,
        order_index: 1,
        estimated_minutes: 30,
        has_prompt: false,
      },
      {
        title: 'Export and review on your phone',
        description: 'What looks good on desktop often looks different on mobile',
        instructions: `Export from Canva:\n• Format: PNG (best quality) or JPG\n• Download all pages\n\nSend to your phone and view in Instagram's photo picker:\n• Does the text look large enough?\n• Is the visual hierarchy clear?\n• Does Slide 1 stop the scroll?\n• Does the last slide have a clear CTA?\n\nIf anything looks off → fix it now in Canva before writing the caption.`,
        order_index: 2,
        estimated_minutes: 10,
        has_prompt: false,
      },
    ],
  },
  {
    name: 'Caption & Post',
    icon: '🚀',
    description: 'Write a caption that drives action',
    order_index: 2,
    tasks: [
      {
        title: 'Write your caption',
        description: 'A great caption extends the value of the visual',
        instructions: `Caption structure:\n\nLine 1 (hook): Restate the hook from slide 1 OR write a complementary hook\n[line break]\nLines 2–5: Expand on the value. 2–4 sentences max.\n[line break]\nCTA: "Save this for later" OR "Comment [X] if you want [Y]" OR "Follow for more [topic]"\n[line break]\nHashtags: 5–10 relevant hashtags (not 30 generic ones)\n\nCaption length: 125–250 words typically performs best.\n\n✗ Don't repeat exactly what's in the slides\n✓ Add context, a personal anecdote, or extra tips the slides didn't have room for`,
        order_index: 0,
        estimated_minutes: 15,
        has_prompt: false,
      },
      {
        title: 'Post at optimal time',
        description: 'Timing affects early engagement and algorithmic push',
        instructions: `Best general posting times:\n• Tuesday–Friday: 9–11am and 5–7pm\n• Monday: 11am–1pm\n• Weekends: 9–11am\n\nYour personal best time:\n→ Instagram Insights → Total Followers → scroll down to "Most active times"\n\nPost and then:\n✓ Add to your Story (tap the share button → Add to Story)\n✓ Respond to every comment in the first hour\n✓ Reply to DMs that come in\n✓ Share to any related group chats`,
        order_index: 1,
        estimated_minutes: 5,
        has_prompt: false,
      },
    ],
  },
]
